### PR TITLE
🐛 Fix type annotation

### LINKED ISSUE #228: TypeError: typing.ClassVar[typing.Type[fastapi_pagination.bases.AbstractParams]] is not valid as type argument
does work with python3.9.8
```
268  File "/builds/app/app.py", line 5, in <module>
268    from fastapi_pagination import add_pagination
269  File "/usr/local/lib/python3.9/site-packages/fastapi_pagination/__init__.py", line 1, in <module>
270    from .api import (
271  File "/usr/local/lib/python3.9/site-packages/fastapi_pagination/api.py", line 12, in <module>
272    from .bases import AbstractPage, AbstractParams
273  File "/usr/local/lib/python3.9/site-packages/fastapi_pagination/bases.py", line 54, in <module>
274    class AbstractPage(GenericModel, Generic[T], ABC):
275  File "pydantic/main.py", line 282, in pydantic.main.ModelMetaclass.__new__
276  File "pydantic/typing.py", line 287, in pydantic.typing.resolve_annotations
277    For use of globalns and localns see the docstring for get_type_hints().
278  File "/usr/local/lib/python3.9/typing.py", line 292, in _eval_type
279    return t._evaluate(globalns, localns, recursive_guard)
280  File "/usr/local/lib/python3.9/typing.py", line 553, in _evaluate
281    type_ = _type_check(
282  File "/usr/local/lib/python3.9/typing.py", line 158, in _type_check
283    raise TypeError(f"{arg} is not valid as type argument")
284TypeError: typing.ClassVar[typing.Type[fastapi_pagination.bases.AbstractParams]] is not valid as type argument 
```

### PR DESCRIPTION
**Pull request by uriyyo**
Fixes #228

### CODE REVIEW

**Comment by jtc42** [comment]
Oh thank god I was just heading over here to try and figure this one out. Hopefully you're able to publish the patch soon! Thanks for this.

**Comment by uriyyo** [comment]
@jtc42 Version `0.9.1` has been released.

**Comment by elpablete** [comment]
Hey, thanks for this. We were going crazy trying to figure this one out!

**Comment by uriyyo** [comment]
@elpablete  Actually it's a `pydantic` issue, I have opened PR to fix this issue)

**Comment by josecsotomorales** [comment]
That was a fast fix, thank you all, love this library.

**Pull request merged**
