### PR TITLE
Add limit to CursorParams.size field

### LINKED ISSUE #1116: Add limit to CursorParams.size field
it would be great, if you add default limit to cursor-based pagination like in the Page one (and, probably, use same description):
```py
class CursorParams(BaseModel, AbstractParams):
    cursor: Optional[str] = Query(None, description="Cursor for the next page")
    size: int = Query(50, ge=0, le=100, description="Page size")

    str_cursor: ClassVar[bool] = True

    def to_raw_params(self) -> CursorRawParams:
        return CursorRawParams(
            cursor=decode_cursor(self.cursor, to_str=self.str_cursor),
            size=self.size,
        )

```

### PR DESCRIPTION
**Pull request by barsikus007**
Resolves #1116

### CODE REVIEW

**Review by uriyyo — APPROVED** [review]

**Comment by nikelborm** [comment]
Yay! 🎉

**Comment by uriyyo** [comment]
@marjoleinveenendaal I'm so sorry to hear that. It's always such a bad situation when I break someone code(

You can customize size using `CustomizedPage`:
```py
from fastapi_pagination.cursor import CursorPage as BaseCursorPage
from fastapi_pagination.customization import UseParamsFields, CustomizedPage


CursorPage = CustomizedPage[
    BaseCursorPage,
    UseParamsFields(
        size=Query(50, ge=0),
    ),
]
```

**Comment by marjoleinveenendaal** [comment]
Thanks! This is less complex than we thought, we will implement it like this!

**Comment by uriyyo** [comment]
Great, please, let me know if you will have any kind of issues 🙏

**Pull request merged**
