### PR TITLE
Replace gt=0 with ge=1 to avoid problems with exclusiveMinimum

### LINKED ISSUE #147: `exclusiveMinimum` causes problems with swagger editor and Azure API Management
The use of `gt` to constrain the query parameters causes the openapi spec validation to fail for example in swagger editor and Azure API Management: https://github.com/tiangolo/fastapi/issues/240, https://github.com/tiangolo/fastapi/issues/3541
As workaround `ge` could be used instead, e.g.
```python
class Page(BasePage[T], Generic[T]):
    page: conint(ge=1)  # type: ignore
    size: conint(ge=1)  # type: ignore
```
instead of
```python
class Page(BasePage[T], Generic[T]):
    page: conint(gt=0)  # type: ignore
    size: conint(gt=0)  # type: ignore
```

### PR DESCRIPTION
**Pull request by Alexander-N**
exclusiveMinimum causes problems with openapi spec validation:
https://github.com/tiangolo/fastapi/issues/240
https://github.com/tiangolo/fastapi/issues/3541

Closes #147

### CODE REVIEW

**Review by uriyyo — APPROVED** [review]
LGTM💫

**Comment by uriyyo** [comment]
@Alexander-N  Looks like you commit not from your github account email. Is it correct email `alexander.niederbuehl@realworld-one.com`?

**Comment by Alexander-N** [comment]
Oh, didn't notice that it's not linked to my account, added it, thanks!

**Comment by uriyyo** [comment]
@Alexander-N This fix has been released under version `0.8.2`. Thanks)

**Pull request merged**
