### PR TITLE
Be able to use `count_query` on `ext.sqlmodels.paginate` and `ext.sqlalchemy.paginate`

### PR DESCRIPTION
**Pull request by moumoutte**
Do not use the __bool__method of count_query as it's not evaluating to a boolean here and instead detect if it's None or not. Also add the count_query as a valid parameter  of `fastapi_pagination.ext.sqlmodel.paginate`

### CODE REVIEW

**Review by uriyyo — COMMENTED** [review]
LGTM!

Could you please also add this feature to `sqlachemy` module?

**Comment by moumoutte** [comment]
If I understand properly your comment, you ask me if I could ad the `count_query` param to the `ext.sqlalchemy.paginate` function ?

I think this param is already present here : 
https://github.com/uriyyo/fastapi-pagination/blob/main/fastapi_pagination/ext/sqlalchemy.py#L241

**Comment by uriyyo** [comment]
@moumoutte My bad, I forgot that it already has `count_query` param 😅

**Comment by uriyyo** [comment]
@moumoutte Thanks for PR!

**Pull request merged**
