### PR TITLE
Use islice instead of slice to create a page.

### LINKED ISSUE #40: [enh] Use islice rather than slice in order to work with generators.
Right now, you select the data using `[]`. `itertools.islice` stills works on sequences, but also works on generators, which is useful when there is a lot of data to go through.

Specifically, I think replacing this line: https://github.com/uriyyo/fastapi-pagination/blob/b6e287524cffa628e76b87e79d5cab0e6f579035/fastapi_pagination/paginator.py#L17 would be sufficient to add the functionality while changing nothing in the existing API.

The line would become

```items=list(it.islice(sequence, raw_params.offset, raw_params.offset + raw_params.limit]),```

(after `import itertools as it`).

What do you think?

### PR DESCRIPTION
**Pull request by masasin**
This allows the use of Generators and other Iterables rather than just Sequences.

Poetry wasn't able to install some packages, so I wasn't able to run the tests locally. Might also be a good idea to add a generator in one of the tests if you're testing with actual objects. (If you were, I wasn't able to find it.)

Closes #40

### CODE REVIEW

**Comment by uriyyo** [comment]
Hi @masasin,
I have just realised that `Page` requires the total count of items, so we will need to convert iterable into list (consume all elements from iterator)

**Comment by masasin** [comment]
The code in the PR only uses the items in the page for the length. (You only end up showing what was taken.) For e.g. infinite iterables, you wouldn't be able to consume everything.

**Comment by uriyyo** [comment]
I think it's will be better to add a separate `paginator` and `Page` which will be able to work with iterables.

The problem that currently pages have `total` attribute which is pointing to the total number of rows rather than to number of rows at paginated result.

**Comment by uriyyo** [comment]
Fixed by #123

**Pull request closed without merging**
