### PR TITLE
Optimize count

### PR DESCRIPTION
**Pull request by thucpk**
Detail: https://gist.github.com/hest/8798884

### CODE REVIEW

**Review by uriyyo — CHANGES_REQUESTED** [review]
LGTM but could you please fix lint errors?

**Comment by uriyyo** [comment]
Hi @thucpk,

Lint is still failing.

I would recommend you to install pre-commit hooks and run them to see where errors are:
```bash
pre-commit install
pre-commit run --all-files
```

**Comment by Alexander-N** [comment]
In https://gist.github.com/hest/8798884 several issues with this solution are mentioned, for example it does not seem to work if there are no filters: https://gist.github.com/hest/8798884#gistcomment-2358429.

**Comment by kigawas** [comment]
You don't really need to optimize the SQL on your own. COUNT with subquery is almost performing the same as COUNT with ID due to database optimization.

See https://dba.stackexchange.com/questions/168022/performance-of-count-in-subquery

**Comment by uriyyo** [comment]
@kigawas Thanks for the explanation, I will close this PR.

**Comment by kigawas** [comment]
@uriyyo If you find your COUNT slow, consider removing any `ORDER BY`.

**Pull request closed without merging**
