### PR TITLE
Bump sqlalchemy-stubs

### PR DESCRIPTION
**Pull request by rushilsrivastava**
Latest version is [0.4](https://pypi.org/project/sqlalchemy-stubs/).

### CODE REVIEW

**Comment by uriyyo** [comment]
Thanks💫

**Comment by rushilsrivastava** [comment]
For sure! I would also totally recommend using [Dependabot](https://dependabot.com/) so that the updates become automatic!

**Comment by uriyyo** [comment]
Looks nice, does `dependabot` have integration with `poetry`?

**Comment by uriyyo** [comment]
It has!

Thanks for such a good advice🙂

**Comment by rushilsrivastava** [comment]
Yup, it [does](https://dependabot.com/blog/announcing-poetry-support/)!

**Pull request merged**
